"""create math ontology tables

Revision ID: 2874d99dec6e
Revises: c53b87867df0
Create Date: 2025-10-04 17:51:03.019134

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2874d99dec6e'
down_revision: Union[str, Sequence[str], None] = 'c53b87867df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('math_tags',
    sa.Column('inception_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('inception_id')
    )
    op.create_table('math_tag_attributes',
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('math_tag_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['math_tag_id'], ['math_tags.inception_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('math_tag_attributes')
    op.drop_table('math_tags')
    # ### end Alembic commands ###
