"""add math_annotation

Revision ID: 10942517fb16
Revises: 2874d99dec6e
Create Date: 2025-11-22 19:18:01.506631

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '10942517fb16'
down_revision: Union[str, Sequence[str], None] = '2874d99dec6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('math_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('math_tag_id', sa.String(), nullable=False),
    sa.Column('sent_id', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.String(), nullable=False),
    sa.Column('char_end', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sent_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('math_entities')
    # ### end Alembic commands ###
