"""add math onthology tables

Revision ID: 257505d4077b
Revises: c53b87867df0
Create Date: 2025-10-04 15:54:37.636915

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '257505d4077b'
down_revision: Union[str, Sequence[str], None] = 'c53b87867df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('math_tags',
    sa.Column('inception_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['math_tags.inception_id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('inception_id')
    )
    op.create_table('math_tag_attributes',
    sa.Column('math_tag_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['math_tag_id'], ['math_tags.inception_id'], ),
    sa.PrimaryKeyConstraint('math_tag_id', 'key', 'language')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('math_tag_attributes')
    op.drop_table('math_tags')
    # ### end Alembic commands ###
