"""add pos_tags table

Revision ID: 77d0ee83eafe
Revises: 2874d99dec6e
Create Date: 2025-10-23 17:14:56.283586

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '77d0ee83eafe'
down_revision = '2874d99dec6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pos_tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tag', sa.String(length=10), nullable=False),
        sa.Column('info_url', sa.String(length=500), nullable=True),
        sa.Column('name_ru', sa.String(length=100), nullable=False),
        sa.Column('name_en', sa.String(length=100), nullable=False),
        sa.Column('examples', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tag')
    )
    op.create_index(op.f('ix_pos_tags_id'), 'pos_tags', ['id'], unique=False)
    op.create_index(op.f('ix_pos_tags_tag'), 'pos_tags', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pos_tags_tag'), table_name='pos_tags')
    op.drop_index(op.f('ix_pos_tags_id'), table_name='pos_tags')
    op.drop_table('pos_tags')
    # ### end Alembic commands ###