"""add grammar annotation tables

Revision ID: c53b87867df0
Revises: 32128bd78507
Create Date: 2025-10-04 15:02:24.990213

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c53b87867df0'
down_revision: Union[str, Sequence[str], None] = '32128bd78507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('lemmatized_text', sa.String(), nullable=False),
    sa.Column('timecode_start', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcript_id', 'position')
    )
    op.create_table('tokens',
    sa.Column('sent_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('whitespace', sa.Boolean(), nullable=False),
    sa.Column('lemma', sa.String(), nullable=False),
    sa.Column('pos', sa.String(), nullable=False),
    sa.Column('conll_str', sa.String(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sent_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('sent_id', 'position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    op.drop_table('sentences')
    # ### end Alembic commands ###
